### PR TITLE
`MODE` command

### PR DESCRIPTION
**Pull request by dlbltv**

### CODE REVIEW

**Comment by mortinso** [comment]
image
just encountered this error, the members should be `a, b, c`

Replication method:
* `a` connects and creates channel `#talk`
* `b` and `c` both connect and join `#talk`
* `b` disconnects
* `b` connects and joins `#talk`

**Comment by mortinso** [comment]
> image just encountered this error, the members should be `a, b, c`
> 
> Replication method:
> 
> * `a` connects and creates channel `#talk`
> * `b` and `c` both connect and join `#talk`
> * `b` disconnects
> * `b` connects and joins `#talk`

If another user joins afterwards, the member list stays fucked
image

**Comment by mortinso** [comment]
I noticed an interesting behavior that I'm not sure was done purposefully. If we follow these steps:
* `a` connects and creates channel `#talk`
* `b` connects
* `a` runs `mode #talk +o b`

 `b` gets operator status even though they're not in the channel. which allows `b` to run `mode` commands on `#talk` without being in the channel

**Comment by mortinso** [comment]
Besides the issues marked above, `mode +k`, `mode +l` and `mode +i` all seem to be working well. `mode +t` can only be tested once we implement the `TOPIC` command.

**Comment by dlbltv** [comment]
Please tell me, how did you disconnect b? I discontected his through QUIT and through CTRL+C, and the result is correct. 

image

But it's on a mac. When I'm in school, I'll check it out on linux. Maybe that's it.

**Comment by mortinso** [comment]
> Please tell me, how did you disconnect b? I discontected his through QUIT and through CTRL+C, and the result is correct.
> 
> image
> But it's on a mac. When I'm in school, I'll check it out on linux. Maybe that's it.

I disconnected both using `^C` and `QUIT` it might be my OS or a package that I have installed that could be fucking it idk. I'm running `Ubuntu 20.4.6 LTS`

**Comment by mortinso** [comment]
I just tested and that still happens to me, whether I'm running valgrind or not

**Comment by dlbltv** [comment]
The problem was repeated on the school computers as well. I'll look into it now.

**Comment by dlbltv** [comment]
Fixed. 

image

**Comment by mortinso** [comment]
Awesome! In like an hour I'll do some testing and if everything's fine we can merge it to the main. :P

**Pull request merged**
